CREATE TABLE USUARIO(
	CodUsuario INT PRIMARY KEY,
	nomeUsuario VARCHAR(13) NOT NULL,
	Senha VARCHAR(254) NOT NULL
)

INSERT INTO USUARIO (CodUsuario,nomeUsuario,Senha)
 VALUES (1,'ADMINISTRADOR','1234')
 
 
SELECT * FROM CONTA WHERE NOMETITULAR LIKE '% %' OR CPF='333.333.333-33'
 
CREATE TABLE CONTA(
  cod INT PRIMARY KEY,
  nomeTitular VARCHAR(256) NOT NULL,
  cpf VARCHAR(14) NOT NULL UNIQUE,
  dataNascimento DATE NOT NULL,
  sexo VARCHAR(1) NOT NULL,
  endereco VARCHAR(256) NOT NULL,
  limite DECIMAL (16,2) NOT NULL,
  limiteTransferencia DECIMAL (16,2) NOT NULL
)

CREATE GENERATOR GEN_CONTA;

CREATE TRIGGER TR_G_CONTA FOR CONTA
ACTIVE BEFORE INSERT POSITION 0
AS
begin
   NEW.cod = GEN_ID(GEN_CONTA, 1);
end

CREATE TABLE EXTRATO(
  cod INT PRIMARY KEY,
  cpf VARCHAR(14) NOT NULL,
  tipoExtrato CHAR(1) NOT NULL,
  transacao VARCHAR(45) NOT NULL,
  dataTransacao DATE NOT NULL,
  valor DECIMAL (16,2) NOT NULL
)

CREATE GENERATOR GEN_EXTRATO;

CREATE TRIGGER TR_G_EXTRATO FOR EXTRATO
ACTIVE BEFORE INSERT POSITION 0
AS
begin
   NEW.cod = GEN_ID(GEN_CONTA, 1);
end
 
CREATE VIEW SOMACREDITO
AS
   SELECT CPF,TIPOEXTRATO,SUM(VALOR) AS SALDO FROM EXTRATO WHERE TIPOEXTRATO='C' GROUP BY CPF,TIPOEXTRATO
   
CREATE VIEW SOMADEBITO
AS
   SELECT CPF,TIPOEXTRATO,SUM(VALOR) AS SALDO FROM EXTRATO WHERE TIPOEXTRATO='D' GROUP BY CPF,TIPOEXTRATO
   
CREATE VIEW SALDO
AS
  SELECT
  SC.CPF,SC.SALDO AS CREDITO,SD.SALDO AS DEBITO,
  SC.SALDO-SD.SALDO AS SALDO
  FROM SOMACREDITO AS SC 
  INNER JOIN SOMADEBITO AS SD
  ON (SC.CPF = SD.CPF)
  
CREATE VIEW VEXTRATO
AS
 SELECT
  C.COD,C.NOMETITULAR,E.CPF,E.TIPOEXTRATO,E.TRANSACAO,E.DATATRANSACAO,E.VALOR
  FROM EXTRATO AS E 
  INNER JOIN CONTA AS C
  ON (E.CPF = C.CPF)
 
